# Generated by Django 6.0 on 2025-12-30 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario (opcional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email del usuario', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Nombre de usuario único (mínimo 3 caracteres)', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='MusicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, help_text='Nombre del artista', max_length=200, null=True)),
                ('artist_id', models.CharField(blank=True, help_text='ID del artista en Spotify', max_length=100, null=True)),
                ('track_name', models.CharField(blank=True, help_text='Nombre de la canción', max_length=200, null=True)),
                ('track_id', models.CharField(help_text='ID de la canción en Spotify (obligatorio)', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se agregó la preferencia')),
                ('user', models.ForeignKey(help_text='Usuario propietario de esta preferencia', on_delete=django.db.models.deletion.CASCADE, related_name='music_preferences', to='api_view_users.user')),
            ],
            options={
                'verbose_name': 'Music Preference',
                'verbose_name_plural': 'Music Preferences',
                'db_table': 'music_preferences',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'track_id')},
            },
        ),
    ]
